# Site settings
title: Ducktyper's blog
description: >
  Anything about programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ducktyper.co.nz" # the base hostname & protocol for your site
github_username:  ducktyper

# Build settings
markdown: kramdown
timezone: Pacific/Auckland

theme: jekyll-theme-slate
show_downloads: false
# google_analytics: ''
