# Site settings
title: Ducktyper's blog
description: > # this means to ignore newlines until "baseurl:"
  Anything about programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ducktyper.co.nz" # the base hostname & protocol for your site
github_username:  ducktyper

# Build settings
markdown: kramdown
timezone: Pacific/Auckland
